package com.juvodu.lmg.model;

import org.apache.commons.lang3.builder.ToStringBuilder;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Spot")
public class Spot{
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private String id;

    @DynamoDBAttribute
    private String name;
    
    @DynamoDBAttribute
    private String description;
    
    @DynamoDBAttribute
    private String longitude;
    
    @DynamoDBAttribute
    private String latitude;
    
    @DynamoDBAttribute
    private String continent;
    
    @DynamoDBAttribute
    private String country;
    
    @DynamoDBAttribute
    private String walk;
    
    @DynamoDBAttribute
    private String waveQuality;
    
    @DynamoDBAttribute
    private String experience;
    
    @DynamoDBAttribute
    private String frequency;
    
    @DynamoDBAttribute
    private String type;
    
    @DynamoDBAttribute
    private String direction;
    
    @DynamoDBAttribute
    private String bottom;
    
    @DynamoDBAttribute
    private String power;
    
    @DynamoDBAttribute
    private String normalDayLength;
    
    @DynamoDBAttribute
    private String goodDayLength;
    
    @DynamoDBAttribute
    private String goodSwellDirection;
    
    @DynamoDBAttribute
    private String goodWindDirection;
    
    @DynamoDBAttribute
    private String swellSize;
    
	@DynamoDBAttribute
    private String bestTidePosition;
    
    @DynamoDBAttribute
    private String bestTideMovement;
    
    @DynamoDBAttribute
    private String weekCrowd;
    
    @DynamoDBAttribute
    private String weekEndCrowd;
    
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getDescription() {
		return description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getLongitude() {
		return longitude;
	}
	
	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}
	
	public String getLatitude() {
		return latitude;
	}
	
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}
	
	public String getContinent() {
		return continent;
	}
	public void setContinent(String continent) {
		this.continent = continent;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getWalk() {
		return walk;
	}
	public void setWalk(String walk) {
		this.walk = walk;
	}
	public String getWaveQuality() {
		return waveQuality;
	}
	public void setWaveQuality(String waveQuality) {
		this.waveQuality = waveQuality;
	}
	public String getExperience() {
		return experience;
	}
	public void setExperience(String experience) {
		this.experience = experience;
	}
	public String getFrequency() {
		return frequency;
	}
	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getDirection() {
		return direction;
	}
	public void setDirection(String direction) {
		this.direction = direction;
	}
	public String getBottom() {
		return bottom;
	}
	public void setBottom(String bottom) {
		this.bottom = bottom;
	}
	public String getPower() {
		return power;
	}
	public void setPower(String power) {
		this.power = power;
	}
	public String getNormalDayLength() {
		return normalDayLength;
	}
	public void setNormalDayLength(String normalDayLength) {
		this.normalDayLength = normalDayLength;
	}
	public String getGoodDayLength() {
		return goodDayLength;
	}
	public void setGoodDayLength(String goodDayLength) {
		this.goodDayLength = goodDayLength;
	}
	public String getGoodSwellDirection() {
		return goodSwellDirection;
	}
	public void setGoodSwellDirection(String goodSwellDirection) {
		this.goodSwellDirection = goodSwellDirection;
	}
	public String getGoodWindDirection() {
		return goodWindDirection;
	}
	public void setGoodWindDirection(String goodWindDirection) {
		this.goodWindDirection = goodWindDirection;
	}
    public String getSwellSize() {
		return swellSize;
	}
	public void setSwellSize(String swellSize) {
		this.swellSize = swellSize;
	}
	public String getBestTidePosition() {
		return bestTidePosition;
	}
	public void setBestTidePosition(String bestTidePosition) {
		this.bestTidePosition = bestTidePosition;
	}
	public String getBestTideMovement() {
		return bestTideMovement;
	}
	public void setBestTideMovement(String bestTideMovement) {
		this.bestTideMovement = bestTideMovement;
	}
	public String getWeekCrowd() {
		return weekCrowd;
	}
	public void setWeekCrowd(String weekCrowd) {
		this.weekCrowd = weekCrowd;
	}
	public String getWeekEndCrowd() {
		return weekEndCrowd;
	}
	public void setWeekEndCrowd(String weekEndCrowd) {
		this.weekEndCrowd = weekEndCrowd;
	}
	
	public String toString() {
	 return new ToStringBuilder(this).
			 append("name", name).
			 append("description", description).
			 append("longitude", longitude).
			 append("latitude", latitude).
			 append("continent", continent).
			 append("country", country).
			 append("walk", walk).
			 append("waveQuality", waveQuality).
			 append("experience", experience).
			 append("frequency", frequency).
			 append("type", type).
			 append("direction", direction).
			 append("bottom", bottom).
			 append("power", power).
			 append("normalDayLength", normalDayLength).
			 append("goodDayLength", goodDayLength).
			 append("goodSwellDirection", goodSwellDirection).
			 append("goodWindDirection", goodWindDirection).
			 append("swellSize", swellSize).
			 append("bestTidePosition", bestTidePosition).
			 append("bestTideMovement", bestTideMovement).
			 append("weekCrowd", weekCrowd).
			 append("weekEndCrowd", weekEndCrowd).
			 toString();
   }
}
